server:
  port: 8081

spring:
  application:
    name: provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurek1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
