server:
  port: 8888

# spring
spring:
  application:
    name: rz-web-tools
  main:
    allow-bean-definition-overriding: true
  # database
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: 12345678

# mybatis
mybatis:
  mapper-locations[0]: classpath*:mapper/**/*.xml