server:
  port: 9090
#================spring
spring:
  application:
    name: vf-video-base
  main:
    allow-bean-definition-overriding: true
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
      username: root
      password: 12345678
#================mybatis
mybatis:
  mapper-locations[0]: classpath*:mapper/**/*.xml
#================dubbo
dubbo:
  application:
    name: vf-video-base
  registry:
    address: nacos://localhost:8848
    username: admin
    password: admin
  scan:
    base-packages: com.vf.video.base.interfaces
  protocol:
    name: dubbo
    port: 16622
  provider:
    filter: dubboUserConfig
