server:
  port: 6060


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chat-app
  ai:
    # com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeChatAutoConfiguration
    dashscope:
      api-key: sk-e5f93a0caa364d548214a24101642a64
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 60s
        # or ASYNC for reactive applications
        type: ASYNC
        sse:
          connections:
            # ??
            server1:
              url: http://localhost:8080